apiVersion: v1
kind: Service
metadata:
  name: fluxo-caixa-api-service
  namespace: fluxocaixa
spec:
  selector:
    app: fluxo-caixa-api-label
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort