apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: fluxocaixa
spec:
  selector:
    app: mongodb-pod-label
  ports:
    - name: http
      port: 27017
      nodePort: 30083
  type: NodePort